name: Update llms.txt Posts Section

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-posts:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          
      - name: Run Posts Updater
        run: go run llms.go
        
      - name: Check for Changes
        id: check_changes
        run: |
          git diff --quiet llms.txt || echo "has_changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add llms.txt 
          git commit -m "docs: update posts section [skip ci]"
          git push
